### ISSUE TITLE
glidefast no longer has it's public domain pointed to sn.

### ISSUE THREAD

**Issue by jacebenson** [NickBelli/ServiceNowResources#3]
glidefast no longer has it's public domain pointed to sn.

Im not srue what you wanna do there.

**Comment by NickBelli** [comment]
Thanks for the heads up @jacebenson - I'll pull it off of here. I've got a few other portals to put on as well, so I'll do them all in one update and put some version notes in the commit.

**Comment by jacebenson** [comment]
nice!

**Comment by NickBelli** [comment]
Removed Glidefast for now - also asked Ashley if there were any public portals so we could keep them on there, but no response so far. I can always add them back later. I'm also considering a secondary page for various Consulting and Third Party integration services as well, but that may be a bigger project.
